### ISSUE TITLE
Broken for v31.0.5

### ISSUE THREAD

**Issue by mgius** [tcprescott/pyz3r#11]
I'm sure you already know this, but it's broken as of the latest release for alttpr.

It looks like you need a BPS patcher and some updates to fetch the new base BPS and apply it as well as how to get the randomizer BPS and apply that.

**Comment by mgius** [comment]
I've got a BPS patcher here: https://github.com/mgius/python-bpspatcher

Needs License, upload to pypi, tests, docs. I was able to patch with the base alttpr hacks but I haven't figured out how to download the BPS for the randomizer components yet so I was only able to verify that the base changes worked.

**Comment by tcprescott** [comment]
I was planning on using this module: https://gitlab.com/Screwtapello/python-bps

I intentionally removed ROM patching capabilities until I have time to update this to use BPS.

**Comment by tcprescott** [comment]
https://alttpr.com/base_rom/settings

This will give you the current md5sum of the base rom, and the path to the BPS file.  This should be cached locally if possible to reduce server load.

https://alttpr.com/api/h/{hash}

This will return the md5sum and base rom bps patch for the game you're trying to patch.  I recommend hitting this endpoint to get the right base rom for the game in question, as festive randomizers or games generated on older version of the game will have a different base rom patch.

**Comment by mgius** [comment]
Wait, I just realized that the BPS path returned by the hash file is the same as the one from base_rom/settings.  Is the "randomizer" patches not BPS as well?

**Comment by mgius** [comment]
> 
> 
> I was planning on using this module: https://gitlab.com/Screwtapello/python-bps

Oh good.  I saw this in pypi but I couldn't find the source repo.  Was good practice to write my own thing anyway.

> I intentionally removed ROM patching capabilities until I have time to update this to use BPS.
> 
> I'm hoping to have some time this weekend.

👍

**Comment by tcprescott** [comment]
> Wait, I just realized that the BPS path returned by the hash file is the same as the one from base_rom/settings. Is the "randomizer" patches not BPS as well?

The second patch that randomizes the game is not BPS, and is still just JSON.
