### ISSUE TITLE
world_state: open not patching

### ISSUE THREAD

**Issue by mgius** [tcprescott/pyz3r#8]
I am unable to patch a game with the Open world state.  I'm more or less following the readme sample docs.  Patches do seem to be applying.  Uncle's text is changed, the chest in link's house is randomized and the opening menu is patched to alttpr custom and to show the validation code items, but initial game state is raining instead of open.

I have tested patched roms in bsnes on windows and snes9x on ARM (raspberry-pi4), same behavior on both.

repro code https://gist.github.com/mgius/48b6c71808da53cdaff57b41b49db1cd

    (retropie-alttpr-SYqaV0nu-py3.7) mgius@ICHABOD:~/src/retropie-alttpr$ python repro.py
    Hash: ZeM48D74Mj
    Code: ['Empty Bottle', 'Ice Rod', 'Pendant', 'Hookshot', 'Hammer']

**Comment by mgius** [comment]
I've done some digging.  this might be a bug on alttpr side.  The request body key for world state is "mode", not "world_state" as returned by the presets.  I updated my repro to submit "mode": "open" instead of world_state and it generated an open rom.

https://github.com/sporchia/alttp_vt_randomizer/blob/master/app/Http/Controllers/RandomizerController.php#L123

**Comment by mgius** [comment]
It looks like it's coming from here. 

https://github.com/sporchia/alttp_vt_randomizer/blob/master/app/Http/Controllers/RandomizerController.php#L123

Are these dict presets meant to be used by the API or are they meant to be used by the web site configurator?

**Comment by mgius** [comment]
Hmm...considering that they expose this route through web.php instead of api.php I think that these configs are meant for the web frontend, not for direct consumption by the API.

https://github.com/sporchia/alttp_vt_randomizer/blob/master/routes/web.php#L7

I'll look into if creating a converter is reasonable later.

**Comment by tcprescott** [comment]
You're correct, the settings endpoint wasn't really designed to be used by the web frontend.  Actually, the entire API really wasn't designed for 3rd party use, it just happened to be used that way.  It's still considered undocumented.
